### PR TITLE
Stop the program crashing at podcasts (or at any new API item), add Podcast & Episode classes

### LINKED ISSUE #132: client.get_chart fails
Discovered when testing/fixing #127 

Calling `client.get_chart()` results in the following stack trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/deezer-python/deezer/client.py", line 213, in get_chart
    return self.get_object(
  File "/deezer-python/deezer/client.py", line 205, in get_object
    return self._process_json(json, parent)
  File "/deezer-python/deezer/client.py", line 120, in _process_json
    value = self._process_json(value, parent)
  File "/deezer-python/deezer/client.py", line 115, in _process_json
    return [self._process_json(i, parent) for i in item["data"]]
  File "/deezer-python/deezer/client.py", line 115, in <listcomp>
    return [self._process_json(i, parent) for i in item["data"]]
  File "/deezer-python/deezer/client.py", line 126, in _process_json
    object_class = self.objects_types[result["type"]]
KeyError: 'podcast'
```

Will attempt to fix and introduce a PR

### PR DESCRIPTION
**Pull request by hithomasmorelli**
Fixes #132

Have so far created an empty `Podcast` class and linked it into `Client`.
Am planning to also take the opportunity to integrate some Podcast API functionality, and add a failsafe to `_process_json` to prevent a new "type" from causing a crash in the future (by just instantiating a `Resource`)

- [x] Include tests for bug fix and new functionality*
- [x] Updated documentation for new feature (docstrings)

(*a test for the failsafe would be a test that the program doesn't crash upon finding an unknown "type" field - not sure on the best way to implement this)

### CODE REVIEW

**Comment by hithomasmorelli** [comment]
Not sure how to achieve 100% coverage on this - how would we test for an unexpected resource?(!)

**Comment by browniebroke** [comment]
We could write a test specificly for the `Client._process_json` or `Client.get_object` method in here:

https://github.com/browniebroke/deezer-python/blob/master/tests/test_client.py

If we write a test for `_process_json`, we don't need to mock anything, but we're testing a bit implementation detail.

If we do it at the `get_object` level, we would need to record a cassette from a simple real resource and edit it to use a replace the resource name by something that doesn't exist.

**Comment by hithomasmorelli** [comment]
I think `Client._process_json` would be better, as that way a cassette couldn't be accidentally overwritten.

**Review by browniebroke — APPROVED** [review]

**Comment by browniebroke** [comment]
Thanks for the great work! 🎉

**Comment by browniebroke** [comment]
@all-contributors please add @hithomasmorelli for bug, code, ideas

**Pull request merged**
