### PR TITLE
Add advanced search method

### PR DESCRIPTION
**Pull request by jnth**
- [x] Include tests for bug fix and new functionality
- [x] Updated documentation for new feature
- [x] Added an entry at the top of History.rst, under the unreleased section

Hi,

A small pull request to add the advanced search method see in [Search page of Deezer API](https://developers.deezer.com/api/search).

For the tests, I updated some tests already presents to be compatible with the `complete_qs` parameter in `requests_mock` module.

### CODE REVIEW

**Comment by jnth** [comment]
I see some errors that do not occurs with my locals python. I'll try to fix that.

**Comment by jnth** [comment]
@browniebroke : I think there's a conflict between black (that use a 88 characters per line by default) and stickler-ci (the limit is 79 chars). I can force black to use the 79-chars limits.

**Comment by browniebroke** [comment]
Hi, thanks for your contribution. Don't worry about stickler CI, I thought I removed it, but apparently it is not the case.

**Comment by browniebroke** [comment]
Also you can ignore Azure pipeline, I'm in the middle of the setup and it's not working yet.

**Comment by browniebroke** [comment]
@jnth released in 0.9.0. Nice to see things [being built with it](https://github.com/jnth/soco-deezer-plugin) btw.

**Comment by jnth** [comment]
Thanks. Your lib is really useful.

**Pull request merged**
